services:
  server:
    build: 
      context: ../..
      dockerfile: src/server/Dockerfile
      
    container_name: ttt-server
    expose: 
      - 8000
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: oursql1234
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      DB_NAME: tictactoe
      DB_POOL_SIZE: 5
      DB_POOL_RECYCLE: 1800

    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ttt-network

    restart: unless-stopped

  caddy:
    image: caddy:latest
    container_name: ttt-caddy
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - server
    networks:
      - ttt-network
    restart: unless-stopped

  mysql:
    image: mysql:latest
    container_name: ttt-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: oursql1234
      MYSQL_DATABASE: tictactoe
      MYSQL_ROOT_HOST: "%"
    expose:
      - 3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ttt-network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-poursql1234",
        ]
      interval: 5s
      timeout: 3s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  mysql_data:

networks:
  ttt-network:
    driver: bridge
